name: QueerTab
version: '${version}'

main: net.saturn.queerTab.QueerTab
api-version: '1.21.11'
load: POSTWORLD

authors: [ PumpkinDev ]

commands:
  pronouns:
    description: Set, clear, or list your pronoun tag.
    usage: /pronouns <set|clear|list> [preset]
    permission: queertab.use
  sexuality:
    description: Set, clear, or list your identity tag.
    usage: /sexuality <set|clear|list> [preset]
    permission: queertab.use